
dataset_source: "@BASE(dataset)"
dataset_target: "@BASE(dataset,scannet)"
dataset_hard: "null"
net: "@BASE(net,pointnet)"
optimizers: "@BASE(optimizers,adamw)"  
losses: "@BASE(losses,crossentropy)"
sampling: "@OPTIONS(uniform;first)"

gpu: [0]
num_workers: 12
project_name: "@OPTIONS(m2s;m2sc;s2m;s2sc;sc2m;sc2s;m2scnn)"
entity: "refrec"
num_classes: 10
test: "@BOOL(false)"
restore_weights: "null"

#haprams
epochs: 25
train_batch_size: 16
val_batch_size: 256
lr: 1e-4
aug: "@BOOL(true)"
pc_input_num: 1024
feat_dims: 1024
occlusions: "@BOOL(true)"
val_split: "@BOOL(false)"
target_cls: "@BOOL(false)"
weighted_ce: "@BOOL(false)"

#haprams for mean teacher
mean_teacher: "@BOOL(false)"
max_weight: 1
warm_up: 15
use_proto: false